services:
  db:
    container_name: sky-ui-db
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - sky-ui-db:/data/postgres

volumes:
  sky-ui-db:
    driver: local
